### ISSUE TITLE
Exception in EmojiParser

### ISSUE THREAD

**Issue by baszero** [vdurmont/emoji-java#32] opened 2016-04-27 09:31 UTC
Just had this exception and I don't know how to fix it.

I run it on Java 1.6:

`
java.lang.ExceptionInInitializerError
	at com.vdurmont.emoji.EmojiParser.getEmojiEndPos(EmojiParser.java:420)
	at com.vdurmont.emoji.EmojiParser.getUnicodeCandidates(EmojiParser.java:382)
	at com.vdurmont.emoji.EmojiParser.parseFromUnicode(EmojiParser.java:355)
	at com.vdurmont.emoji.EmojiParser.parseToHtmlDecimal(EmojiParser.java:213)
	at com.vdurmont.emoji.EmojiParser.parseToHtmlDecimal(EmojiParser.java:172)
	at com.zwischengas.resource.teaser.auto2.AutoTeaserPage2016Resource.addElementsForRead(AutoTeaserPage2016Resource.java:754)
	at com.zwischengas.resource.GeneralZwischengasResource.getContentXML(GeneralZwischengasResource.java:590)
	at com.zwischengas.resource.GeneralZwischengasResource.getView(GeneralZwischengasResource.java:416)
	at org.wyona.yanel.servlet.YanelServlet.getContent(YanelServlet.java:599)
	at org.wyona.yanel.servlet.YanelServlet.doGet(YanelServlet.java:429)
	at org.wyona.yanel.servlet.YanelServlet.service(YanelServlet.java:333)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.wyona.yanel.servlet.communication.YanelFilter.doFilter(YanelFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:61)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:55)
	at com.vdurmont.emoji.EmojiLoader.inputStreamToString(EmojiLoader.java:51)
	at com.vdurmont.emoji.EmojiLoader.loadEmojis(EmojiLoader.java:36)
	at com.vdurmont.emoji.EmojiManager.<clinit>(EmojiManager.java:29)
`

**Comment by vdurmont** [comment] 2016-04-27 14:34
Hi!

It looks like the error is caused by:
```
java.lang.NullPointerException at java.io.Reader.<init>(Reader.java:61)
at java.io.InputStreamReader.<init>(InputStreamReader.java:55)
at com.vdurmont.emoji.EmojiLoader.inputStreamToString(EmojiLoader.java:51)
at com.vdurmont.emoji.EmojiLoader.loadEmojis(EmojiLoader.java:36)
at com.vdurmont.emoji.EmojiManager.<clinit>(EmojiManager.java:29) 
```

It means that the library cannot find the emoji database. *emoji-java* has a file in `./src/main/resources/emojis.json` that it tries to load to get the emojis.

Which version are you using?
How did you add *emoji-java* to your project? Maven? Gradle?

**Comment by baszero** [comment] 2016-04-27 14:58
Hi, thanks.
I'm using commit 05dacd9c7f4bb9965c4fc5edaf1e2111a2991d86
and I just put the source directly in my java project (as a first test). So I didn't load it as external lib.

**Comment by vdurmont** [comment] 2016-04-27 16:15
Then you will have to modify this line https://github.com/vdurmont/emoji-java/blob/master/src/main/java/com/vdurmont/emoji/EmojiManager.java#L18 to specify the right path in your application!

PS: I strongly suggest that you use a package manager such as Maven to avoid that kind of problems.

**Comment by baszero** [comment] 2016-04-27 18:16
Yes of course, I'll try it with the regular Maven build then.
Thanks for your help so far.

**Comment by vdurmont** [comment] 2016-05-22 17:58
Closing this issue since it seems it's been solved.
Feel free to reopen if you still have a problem.

**Closed by vdurmont** 2016-05-22 17:58 UTC
